---
title: "snpanalysis"
output: html_document
---

```{r load include=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(readxl)
library('corrr')
library(ggcorrplot)
library(factoextra)
library("FactoMineR")
library(missMDA)
library(wesanderson)
library("ggfortify")
library(ggcorrplot)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(readr)
library(lme4) 
library(ggplot2)
library(ggstatsplot)
```

```{r read}
file_path <- "~/sapphire/data/serum_vit_D_study_with_lab_results.xlsx" 
data_summer <- read_excel(file_path, sheet = "ScreeningDataCollectionSummer")
data_winter <- read_excel(file_path, sheet = "ScreeningDataCollectionWinter")
data_6weeks <- read_excel(file_path, sheet = "ScreeningDataCollection6Weeks")
sun_expos <- read.csv("~/sapphire/data/sun_expos_data/sun_expos_long.csv")
sun_expos_summer <- sun_expos[sun_expos$collection_period == 'Summer', ]
sun_expos_winter <- sun_expos[sun_expos$collection_period == 'Winter', ]
sun_expos_6Weeks <- sun_expos[sun_expos$collection_period == '6Weeks', ]
summer_winter <- read.csv("~/sapphire/SAfrADMIX/wide_data.csv")
longform <- read.csv("~/sapphire/SAfrADMIX/long.csv")
```

```{r geneticpca}
rm(list = ls())
# Set working directory
setwd("~/sapphire/SAfrADMIX")

system("./plink --bfile SAfrADMIX --nonfounders --no-pheno         --allow-no-sex --recode --out ADAPTmap_TOP")

system("./plink --allow-no-sex --nonfounders --file ADAPTmap_TOP --distance-matrix --out dataForPCA")

# PCA
# Load data
dist_populations<-read.table("dataForPCA.mdist",header=F)

# Extract ethnicity names
fam <- data.frame(famids=read.table("dataForPCA.mdist.id")[,1])
# Extract individual names
famInd <- data.frame(IID=read.table("dataForPCA.mdist.id")[,2])

mds_populations <- cmdscale(dist_populations,eig=T,5)

# Extract the eigen vectors
eigenvec_populations <- cbind(fam,famInd,mds_populations$points)
eigenvec_populations <- eigenvec_populations%>%
  mutate(Ethnicity = substr(famids, start = 1, stop = 2))

# Proportion of variation captured by each eigen vector
eigen_percent <- round(((mds_populations$eig)/sum(mds_populations$eig))*100,2)

ggplot(data = eigenvec_populations) +
  geom_point(mapping = aes(x = `1`, y = `2`,color = Ethnicity), show.legend = TRUE ) +
  geom_hline(yintercept = 0, linetype="dotted") +
  geom_vline(xintercept = 0, linetype="dotted") +
  labs(title = "SAPPHIRE genetic pca",
       x = paste0("Principal component 1 (",eigen_percent[1]," %)"),
       y = paste0("Principal component 2 (",eigen_percent[2]," %)")) +
  theme_minimal()

```

what if we take the absolute value of the difference between the winter inner arm and the summer forehead? Or the difference between the highest MI value and lowest MI value regardless of season or location? 
```{r cleaning}
summer_winter <- summer_winter %>%
  mutate(TanDiff = MedianForeheadM.summer - MedianInnerArmM.winter)

plot(summer_winter$TanDiff)
```


```{r snps}
#change participant centre id to IID 
summer_winter$ParticipantCentreID <- gsub("([A-Z]{4})0([0-9]{2})", "\\1\\2", summer_winter$ParticipantCentreID)
names(summer_winter)[names(summer_winter) == "ParticipantCentreID"] <- "IID"
summer_winter$IID <- gsub("VDKH([0-9]+)", "VDKHS\\1", summer_winter$IID)

#create FID 
summer_winter <- summer_winter %>%
  mutate(FID = case_when(
    grepl("^VDTG", IID) ~ gsub("^VDTG", "CM", IID),
    grepl("^VDKHS", IID) ~ gsub("^VDKHS", "XH", IID),
    TRUE ~ IID))
```

```{r lj}
eigen_join <- left_join(summer_winter, eigenvec_populations, by = "IID")
names(eigen_join)[names(eigen_join) == "1"] <- "PC1"
names(eigen_join)[names(eigen_join) == "2"] <- "PC2"

ggplot(eigen_join, aes(x = PC1, y = PC2)) +
  # Points with fill based on MI value, color based on ethnic group
  geom_point(aes(color = Ethnicity, fill = TanDiff), shape = 21, size = 3, alpha = 0.7) +
  # Add ellipses for each ethnic group
  stat_ellipse(aes(color = Ethnicity), level = 0.95) +
  # Optionally adjust color palette
  scale_fill_viridis_c() + # or scale_fill_gradientn() for a custom color palette
  scale_color_manual(values = c('CM' = 'blue', 'XH' = 'red')) +
  theme_minimal() +
  labs(title = "Scatter Plot with Ellipses by Ethnic Group and MI",
       x = "X Axis Label",
       y = "Y Axis Label",
       color = "Ethnic Group",
       fill = "MI Value")

```

```{r lm}

model1 <- lm(MedianForeheadM ~ MedianForeheadE*Ethnicity, data = longform)
summary(model1)


# Generate predictions from the model
longform$predicted <- predict(model1, newdata = longform)

# Plot using ggplot
ggplot(longform, aes(x = MedianForeheadE, y = MedianForeheadM, color = Ethnicity)) +
  geom_point(alpha = 0.5) +  # Scatter plot for actual data
  geom_line(aes(y = predicted), size = 1) +  # Add predicted regression lines
  labs(title = "Interaction between MedianForeheadE and Ethnicity",
       x = "Median Forehead E",
       y = "Median Forehead M",
       color = "Ethnicity") +
  theme_minimal() +
  theme(legend.position = "top")  # Adjust the legend position if necessary
model <- lm(Pigmentation ~ Season + (1 | Subject), data = df)
```


```{r prediction}

```



